
// This file is automatically generated

export const METADATA = {
  "name": "@testbase/agents",
  "version": "0.1.0",
  "versions": {
    "@testbase/agents": "0.1.0"
  }
};

export default METADATA;
