
// This file is automatically generated

export const METADATA = {
  "name": "computer-agents-openai",
  "version": "0.4.4",
  "versions": {
    "computer-agents-openai": "0.4.4",
    "openai": "^5.20.2"
  }
};

export default METADATA;
