
// This file is automatically generated

export const METADATA = {
  "name": "computer-agents-core",
  "version": "0.3.0",
  "versions": {
    "computer-agents-core": "0.3.0",
    "@openai/codex-sdk": "^0.47.0",
    "openai": "^5.20.2"
  }
};

export default METADATA;
